<?php
    require('fpdf.php');
    require 'bd.php';
    $id = $_GET["id"];
    $consulta = "SELECT * FROM postulantes WHERE documento = '$id'";
    $resultado = mysqli_query($conexion, $consulta);
    $consultab = "SELECT * FROM requisitos WHERE dni = '$id' AND concepto = 'Foto'";
    $resultadob = mysqli_query($conexion, $consultab);
    $consultac = "SELECT * FROM requisitos WHERE dni = '$id' AND concepto = 'Foto'";
    $resultadoc = mysqli_query($conexion, $consultac);
    class PDF extends FPDF {
        function Header() {
            $this->Image('assets/img/logo.png',8,10,20);
            $this->Cell(-2);
            $this->SetFont('helvetica','B',16);
            $this->Cell(112,25,utf8_decode('Universidad Nacional de Cañete'),0,0,'R');
            $this->Ln(10);
            $this->SetFont('helvetica','B',10);
            $this->Cell(110,20,utf8_decode('Examen de admisión 2023'),0,0,'R');
            $this->Image('assets/img/logo.png',151,10,20);
            $this->Ln(-10);
            $this->Cell(141);
            $this->SetFont('helvetica','B',16);
            $this->Cell(112,25,utf8_decode('Universidad Nacional de Cañete'),0,0,'R');
            $this->Ln(10);
            $this->Cell(143);
            $this->SetFont('helvetica','B',10);
            $this->Cell(110,20,utf8_decode('Examen de admisión 2023'),0,0,'R');
            $this->Ln(22);
            $this->SetFont('helvetica','B',12);
            $this->Cell(-2);
            $this->Cell(139,10,utf8_decode('CARNÉ DE POSTULANTE - DECLARACIÓN JURADA 2023'),0,0,'C');
            $this->Cell(4);
            $this->Cell(139,10,utf8_decode('CARNÉ DE POSTULANTE - DECLARACIÓN JURADA 2023'),0,0,'C');
        }
    }
    $pdf = new PDF();
    $pdf->AliasNbPages();
    $pdf->AddPage('L');
    $pdf->Ln(10);
    $pdf->Cell(-2);
    $pdf->SetFont('helvetica','B',10);
    $pdf->Cell(17,6,utf8_decode('LOCAL:'),0,0,'L');
    $pdf->SetFont('helvetica','',10);
    $pdf->Cell(62,6,utf8_decode('Sede principal'),0,0,'L');
    while ($rowb = $resultadob->fetch_assoc()){
        $pdf->Image('assets/requisitos/'.$rowb['archivo'],117,52,30);
    }
    $pdf->SetFont('helvetica','B',10);
    $pdf->Cell(64);
    $pdf->Cell(17,6,utf8_decode('LOCAL:'),0,0,'L');
    $pdf->SetFont('helvetica','',10);
    $pdf->Cell(62,6,utf8_decode('Sede principal'),0,0,'L');
    while ($rowc = $resultadoc->fetch_assoc()){
        $pdf->Image('assets/requisitos/'.$rowc['archivo'],260,52,30);
    }
    while ($row = $resultado->fetch_assoc()){
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(38,6,utf8_decode('HORA DE INGRESO:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(41,6,utf8_decode('08:00 am'),0,0,'L');
        $pdf->Cell(64);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(38,6,utf8_decode('HORA DE INGRESO:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(41,6,utf8_decode('08:00 am'),0,0,'L');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(50,6,utf8_decode('CÓDIGO DE POSTULANTE:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(41,6,utf8_decode($row['documento']),0,0,'L');
        $pdf->Cell(52);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(50,6,utf8_decode('CÓDIGO DE POSTULANTE:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(41,6,utf8_decode($row['documento']),0,0,'L');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(41,6,utf8_decode('APELLIDO PATERNO:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(50,6,utf8_decode($row['apellidoPaterno']),0,0,'L');
        $pdf->Cell(52);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(41,6,utf8_decode('APELLIDO PATERNO:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(50,6,utf8_decode($row['apellidoPaterno']),0,0,'L');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(41,6,utf8_decode('APELLIDO MATERNO:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(50,6,utf8_decode($row['apellidoMaterno']),0,0,'L');
        $pdf->Cell(52);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(41,6,utf8_decode('APELLIDO MATERNO:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(50,6,utf8_decode($row['apellidoMaterno']),0,0,'L');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(23,6,utf8_decode('NOMBRES:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(68,6,utf8_decode($row['nombres']),0,0,'L');
        $pdf->Cell(52);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(23,6,utf8_decode('NOMBRES:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(68,6,utf8_decode($row['nombres']),0,0,'L');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(27,6,utf8_decode('MODALIDAD:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(112,6,utf8_decode($row['modalidad']),0,0,'L');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(27,6,utf8_decode('MODALIDAD:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(112,6,utf8_decode($row['modalidad']),0,0,'L');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(39,6,utf8_decode('FECHA DE EXAMEN:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(100,6,utf8_decode('12-02-2023'),0,0,'L');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(39,6,utf8_decode('FECHA DE EXAMEN:'),0,0,'L');
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(100,6,utf8_decode('12-02-2023'),0,0,'L');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(139,6,utf8_decode('DECLARACIÓN JURADA'),0,0,'L');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','B',10);
        $pdf->Cell(139,6,utf8_decode('DECLARACIÓN JURADA'),0,0,'L');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('- La información consignada al momento de inscribirme es verdadera y de mi entera'),0,0,'J');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('- La información consignada al momento de inscribirme es verdadera y de mi entera'),0,0,'J');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('responsabilidad.'),0,0,'J');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('responsabilidad.'),0,0,'J');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('- Conozco y acepto todas las disposiciones del Reglamento General de Admisión 2023'),0,0,'J');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('- Conozco y acepto todas las disposiciones del Reglamento General de Admisión 2023'),0,0,'J');
        $pdf->Ln(6);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('al cual me someto.'),0,0,'J');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('al cual me someto.'),0,0,'J');
        $pdf->Ln(15);
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('_____________________'),0,0,'C');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('_____________________'),0,0,'C');
        $pdf->Ln();
        $pdf->Cell(-2);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('Firma del postulante'),0,0,'C');
        $pdf->Cell(4);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(139,6,utf8_decode('Firma del postulante'),0,0,'C');
        $pdf->Ln(10);
        $pdf->Cell(37);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(25,25,utf8_decode(''),1,0,'C');
        $pdf->Cell(10);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(25,25,utf8_decode(''),1,0,'C');
        $pdf->Ln(27);
        $pdf->Cell(37);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(25,5,utf8_decode('Medio derecho'),0,0,'C');
        $pdf->Cell(10);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(25,5,utf8_decode('Índice derecho'),0,0,'C');
        $pdf->Ln(-27);
        $pdf->Cell(180);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(25,25,utf8_decode(''),1,0,'C');
        $pdf->Cell(10);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(25,25,utf8_decode(''),1,0,'C');
        $pdf->Ln(27);
        $pdf->Cell(180);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(25,5,utf8_decode('Medio derecho'),0,0,'C');
        $pdf->Cell(10);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(25,5,utf8_decode('Índice derecho'),0,0,'C');
        $pdf->Ln(-35);
        $pdf->Cell(130);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        $pdf->Ln(7);
        $pdf->Cell(130);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        $pdf->Ln(7);
        $pdf->Cell(130);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        $pdf->Ln(7);
        $pdf->Cell(130);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        $pdf->Ln(7);
        $pdf->Cell(130);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        ////
        $pdf->Ln(-27);
        $pdf->Cell(273);
        $pdf->SetFont('helvetica','',10);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        $pdf->Ln(7);
        $pdf->Cell(273);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        $pdf->Ln(7);
        $pdf->Cell(273);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        $pdf->Ln(7);
        $pdf->Cell(273);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
        $pdf->Ln(7);
        $pdf->Cell(273);
        $pdf->Cell(7,7,utf8_decode(''),1,0,'C');
    }
    $pdf->Output();
?>